const { Client } = require('pg');

const client = new Client({
  connectionString: 'postgresql://postgres.rfpqwypgpminypfukarq:cellquest!23@aws-1-ap-northeast-1.pooler.supabase.com:5432/postgres',
  ssl: { rejectUnauthorized: false }
});

const sql = `
-- Clear mock data
DELETE FROM public.doctors;
DELETE FROM public.patients;
DELETE FROM public.appointments;

-- Ensure admin_users table and credentials exist
CREATE TABLE IF NOT EXISTS public.admin_users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email TEXT NOT NULL,
    password_hash TEXT NOT NULL
);

-- Keep admin credentials
DELETE FROM public.admin_users;
INSERT INTO public.admin_users (email, password_hash) VALUES ('admin@cellquestindia.com', 'Admin@2024');

-- Create test_prices table for admin-controlled pricing
CREATE TABLE IF NOT EXISTS public.test_prices (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    test_name TEXT NOT NULL UNIQUE,
    current_price TEXT NOT NULL,
    old_price TEXT,
    discount TEXT,
    updated_at TIMESTAMP DEFAULT NOW()
);

ALTER TABLE public.test_prices DISABLE ROW LEVEL SECURITY;

-- Add email column to appointments if not present
DO $$ BEGIN
  ALTER TABLE public.appointments ADD COLUMN IF NOT EXISTS email TEXT;
EXCEPTION WHEN OTHERS THEN NULL;
END $$;

ALTER TABLE public.doctors DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.patients DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.appointments DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.admin_users DISABLE ROW LEVEL SECURITY;
`;

async function main() {
  try {
    await client.connect();
    console.log('Connected to DB');
    await client.query(sql);
    console.log('SQL executed! Mock data cleared, test_prices table created.');
  } catch (err) {
    console.error('Error executing SQL', err);
  } finally {
    await client.end();
  }
}
main();
