const { Client } = require('pg');

const client = new Client({
  connectionString: 'postgresql://postgres.rfpqwypgpminypfukarq:cellquest!23@aws-1-ap-northeast-1.pooler.supabase.com:5432/postgres',
  ssl: { rejectUnauthorized: false }
});

const sql = `
-- 1. Create Doctors Table
CREATE TABLE IF NOT EXISTS public.doctors (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    specialty TEXT NOT NULL,
    phone TEXT,
    email TEXT,
    status TEXT DEFAULT 'Active',
    joined TEXT
);

-- 2. Create Patients Table
CREATE TABLE IF NOT EXISTS public.patients (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    age INT,
    gender TEXT,
    phone TEXT,
    test TEXT,
    doctor TEXT,
    date TEXT,
    status TEXT DEFAULT 'Pending'
);

-- 3. Create Appointments Table
CREATE TABLE IF NOT EXISTS public.appointments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient TEXT NOT NULL,
    phone TEXT,
    email TEXT,
    test TEXT,
    doctor TEXT,
    date TEXT,
    time TEXT,
    status TEXT DEFAULT 'Pending'
);

-- Add email column if it doesn't exist (for existing tables)
DO $$ BEGIN
  ALTER TABLE public.appointments ADD COLUMN IF NOT EXISTS email TEXT;
EXCEPTION WHEN OTHERS THEN NULL;
END $$;

-- 4. Initial Mock Data
DELETE FROM public.doctors;
DELETE FROM public.patients;
DELETE FROM public.appointments;

INSERT INTO public.doctors (name, specialty, phone, email, status, joined) VALUES
('Dr. Rajiv Sharma', 'Pathology', '+91 98765 43210', 'rsharma@cellquest.in', 'Active', 'Jan 2023'),
('Dr. Priya Verma', 'Biochemistry', '+91 87654 32109', 'pverma@cellquest.in', 'Active', 'Mar 2023');

INSERT INTO public.patients (name, age, gender, phone, test, doctor, date, status) VALUES
('Rajesh Kumar', 45, 'Male', '+91 98765 11111', 'Complete Blood Count', 'Dr. Sharma', '2026-04-22', 'Completed'),
('Priya Singh', 32, 'Female', '+91 87654 22222', 'Lipid Profile', 'Dr. Verma', '2026-04-22', 'In Progress');

INSERT INTO public.appointments (patient, phone, test, doctor, date, time, status) VALUES
('Rajesh Kumar', '+91 98765 11111', 'Complete Blood Count', 'Dr. Sharma', '2026-04-22', '09:00 AM', 'Completed'),
('Priya Singh', '+91 87654 22222', 'Lipid Profile', 'Dr. Verma', '2026-04-22', '10:30 AM', 'In Progress');

-- Admin Credentials stored in a tiny table
CREATE TABLE IF NOT EXISTS public.admin_users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email TEXT NOT NULL,
    password_hash TEXT NOT NULL
);

DELETE FROM public.admin_users;

INSERT INTO public.admin_users (email, password_hash) VALUES ('admin@cellquestindia.com', 'Admin@2024');

ALTER TABLE public.doctors DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.patients DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.appointments DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.admin_users DISABLE ROW LEVEL SECURITY;
`;

async function main() {
  try {
    await client.connect();
    console.log('Connected to DB');
    await client.query(sql);
    console.log('SQL executed!');
  } catch (err) {
    console.error('Error executing SQL', err);
  } finally {
    await client.end();
  }
}
main();
